FROM golang:1.7.3

ENV REPO deitch/yq
ENV FULLREPO github.com/${REPO}

# we work in src of GOPATH
WORKDIR /go/src

RUN mkdir -p /go/src/${FULLREPO}
COPY . /go/src/${FULLREPO}

WORKDIR /go/src/${FULLREPO}

RUN curl https://glide.sh/get | sh
RUN glide install
# build for multiple OSes
RUN GOOS=linux GOARCH=amd64 go build -o yq-linux-amd64
RUN GOOS=darwin GOARCH=amd64 go build -o yq-darwin-amd64
RUN GOOS=windows GOARCH=amd64 go build -o yq-windows-amd64.exe

CMD [ "./yq-linux-amd64" ]
